apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: prod project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  creationTimestamp: null
  name: prod
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: apps/*/overlays/**-prod/values.yaml
      repoURL: https://github.com/otavio-ab/argocd
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ path[1] }}' # airflow
      name: '{{ path[1] }}-{{ path[3] }}' # airflow-data
      namespace: argocd
    spec:
      project: prod
      destination:
        namespace: '{{ path[1] }}-{{ path[3] }}' # airflow-data-engineer-prod
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: https://github.com/otavio-ab/argocd
        path: '{{ path }}/../../base'
        targetRevision: 'main'
        helm:
          valueFiles:
            - 'values.yaml'
      syncPolicy:
        automated: null
        syncOptions:
        - CreateNamespace=true