airflow:
  executor: CeleryExecutor

  images:
    airflow:
      tag: 2.9.0-python3.12

  # Necessary to ArgoCD execute database migrations
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
    jobAnnotations:
      "argocd.argoproj.io/hook": Sync