executor: KubernetesExecutor

images:
  airflow:
    tag: 2.9.0-python3.12

createuserjob:  
  useHelmHooks: false  
  applyCustomEnv: false
migratedatabasejob:  
  enabled: true  
  useHelmHooks: false